import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700'] });

export const metadata = {
  title: "AgriCart",
  description: "Generated by create next app, develop by mr.zvie",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/Agricart.ico' />  
      </head>
      <body className={roboto.className}>
        <main className="max-w-6xl mx-auto">
          {children}
          </main>
      </body>
    </html>
  );
}